version: 2
updates:
  - package-ecosystem: mix
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
      day: saturday
  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
      day: saturday
